force-app/main/default/objects/Product2/fields/NAT_Category__c.field-meta.xml
<CustomField>
    <fullName>NAT_Category__c</fullName>
    <description>Product Category</description>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>beauty</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/NAT_ExternalID__c.field-meta.xml
<CustomField>
    <fullName>NAT_ExternalID__c</fullName>
    <externalId>true</externalId>
    <label>NAT External ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/NAT_Price__c.field-meta.xml
<CustomField>
    <fullName>NAT_Price__c</fullName>
    <description>Product Price</description>
    <label>Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/NAT_ProductSyncHelper.cls
public with sharing class NAT_ProductSyncHelper {

    //Business limits
    private static final Integer CATEGORY_PRODUCT_LIMIT = 100;
    private static final Integer CATEGORY_PRICE_LIMIT = 10000;

    public static void syncProducts() {

        List<Product2> products = NAT_ProductAPI.fetchProducts();

        if(!products.isEmpty()){

            List<Product2> productsToUpsert = new List<Product2>();

            // Categorize and filter by business rule
    
            //Map products by category
            Map<String, List<Product2>> productsByCategory = new Map<String, List<Product2>>();
    
            for (Product2 product : products) {
                if (!productsByCategory.containsKey(product.NAT_Category__c)) {
                    productsByCategory.put(product.NAT_Category__c, new List<Product2>());
                }
                productsByCategory.get(product.NAT_Category__c).add(product);
            }
    
            //Check category limits
            for (String category : productsByCategory.keySet()) {
                List<Product2> categoryProducts = productsByCategory.get(category);
                List<Product2> limitedList = new List<Product2>();
                Decimal priceSum = 0;
    
                for (Product2 product : categoryProducts) {
                    if (limitedList.size() >= CATEGORY_PRODUCT_LIMIT || priceSum + product.NAT_Price__c > CATEGORY_PRICE_LIMIT){
                        break;
                    } 
                    limitedList.add(product);
                    priceSum += product.NAT_Price__c;
                }
    
                for (Product2 product : limitedList) {
                    productsToUpsert.add(product);
                }
            }
    
            //Upsert products filtering by their external ID
            if (!productsToUpsert.isEmpty()) {
                upsert productsToUpsert NAT_ExternalID__c;
            }
        }
    }
}