force-app/main/default/objects/Product2/fields/NAT_Brand__c.field-meta.xml
<CustomField>
    <fullName>NAT_Brand__c</fullName>
    <description>Product Brand</description>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Essence</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/NAT_Category__c.field-meta.xml
<CustomField>
    <fullName>NAT_Category__c</fullName>
    <description>Product Category</description>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>beauty</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/NAT_ExternalID__c.field-meta.xml
<CustomField>
    <fullName>NAT_ExternalID__c</fullName>
    <externalId>true</externalId>
    <label>NAT External ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/NAT_Price__c.field-meta.xml
<CustomField>
    <fullName>NAT_Price__c</fullName>
    <description>Product Price</description>
    <label>Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/NAT_Stock__c.field-meta.xml
<CustomField>
    <fullName>NAT_Stock__c</fullName>
    <description>Number of units in stock</description>
    <label>Stock</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/NAT_ThumbnailURL__c.field-meta.xml
<CustomField>
    <fullName>NAT_ThumbnailURL__c</fullName>
    <label>Thumbnail URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/NAT_ProductSyncController.cls
public with sharing class NAT_ProductSyncController {
    @AuraEnabled
    public static void refreshProductData() {
        NAT_ProductSyncHelper.syncProducts();
    }

    @AuraEnabled(cacheable=true)
    public static List<Product2> getProducts() {
        return Database.query('SELECT Id, Name, NAT_Category__c, NAT_Brand__c, NAT_Price__c, NAT_Stock__c, NAT_ThumbnailURL__c FROM Product2 WHERE NAT_ExternalID__c != null');
    }
}